services:
  postgres:
    image: postgres:15-alpine
    container_name: db
    env_file:
      - .env.postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGUSER=${PGUSER}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  fullfill:
    build:
      context: apps/add_data/.
      dockerfile: Dockerfile
      args:
        DB_USER: ${POSTGRES_USER}
        DB_PASS: ${POSTGRES_PASSWORD}
        DB_PORT: ${POSTGRES_PORT}
        DB_NAME: ${DB_NAME}
    container_name: fullfill